"""Add ondelete=cascade to transaction inputs, outputs, unspent

Revision ID: a79fed245af3
Revises: fc79976471d3
Create Date: 2024-08-30 20:00:48.841664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79fed245af3'
down_revision: Union[str, None] = 'fc79976471d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blockchain_input_txid_fkey', 'blockchain_input', type_='foreignkey')
    op.create_foreign_key('blockchain_input_txid_fkey', 'blockchain_input', 'blockchain_transaction', ['txid'], ['id'], ondelete='CASCADE')
    op.drop_constraint('blockchain_output_txid_fkey', 'blockchain_output', type_='foreignkey')
    op.create_foreign_key('blockchain_output_txid_fkey', 'blockchain_output', 'blockchain_transaction', ['txid'], ['id'], ondelete='CASCADE')
    op.alter_column('blockchain_unspent', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('blockchain_unspent_txid_vout_fkey', 'blockchain_unspent', type_='foreignkey')
    op.create_foreign_key('blockchain_unspent_txid_vout_fkey', 'blockchain_unspent', 'blockchain_output', ['txid', 'vout'], ['txid', 'vout'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blockchain_unspent_txid_vout_fkey', 'blockchain_unspent', type_='foreignkey')
    op.create_foreign_key('blockchain_unspent_txid_vout_fkey', 'blockchain_unspent', 'blockchain_output', ['txid', 'vout'], ['txid', 'vout'])
    op.alter_column('blockchain_unspent', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('blockchain_output_txid_fkey', 'blockchain_output', type_='foreignkey')
    op.create_foreign_key('blockchain_output_txid_fkey', 'blockchain_output', 'blockchain_transaction', ['txid'], ['id'])
    op.drop_constraint('blockchain_input_txid_fkey', 'blockchain_input', type_='foreignkey')
    op.create_foreign_key('blockchain_input_txid_fkey', 'blockchain_input', 'blockchain_transaction', ['txid'], ['id'])
    # ### end Alembic commands ###
