"""Drop Unspent foreign key to Transaction

Revision ID: 35fc7eadd533
Revises: fa2219e1174b
Create Date: 2024-08-31 20:26:14.350943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fc7eadd533'
down_revision: Union[str, None] = 'fa2219e1174b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blockchain_unspent_txid_vout_fkey', 'blockchain_unspent', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('blockchain_unspent_txid_vout_fkey', 'blockchain_unspent', 'blockchain_output', ['txid', 'vout'], ['txid', 'vout'], ondelete='CASCADE')
    # ### end Alembic commands ###
