"""Manage unique constraints (user.username, unspent.addrstr)

Revision ID: 4914c813997a
Revises: 7fef32977aad
Create Date: 2024-07-26 11:52:42.680847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4914c813997a'
down_revision: Union[str, None] = '7fef32977aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blockchain_unspent_addresstr_key', 'blockchain_unspent', type_='unique')
    op.create_unique_constraint('user_username_uk', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_uk', 'user', type_='unique')
    op.create_unique_constraint('blockchain_unspent_addresstr_key', 'blockchain_unspent', ['addresstr'])
    # ### end Alembic commands ###
