"""Add created_at, apiservice, Input.is_segwit columns for explorer tables

Revision ID: 62222eef7aa7
Revises: a91a26e21987
Create Date: 2024-08-18 16:00:45.967002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62222eef7aa7'
down_revision: Union[str, None] = 'a91a26e21987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_input', sa.Column('is_segwit', sa.Boolean(), nullable=False))
    op.add_column('blockchain_transaction', sa.Column('apiservice', sa.String(), nullable=False))
    op.add_column('blockchain_transaction', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'created_at')
    op.drop_column('blockchain_transaction', 'apiservice')
    op.drop_column('blockchain_input', 'is_segwit')
    # ### end Alembic commands ###
