"""Rename User aeskeys columns, add kdf_options

Revision ID: a91a26e21987
Revises: f88ec9141ec2
Create Date: 2024-08-04 12:41:33.670030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a91a26e21987'
down_revision: Union[str, None] = 'f88ec9141ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'aeskey_encrypted', new_column_name='ckey_encrypted')
    op.alter_column('user', 'aeskey_sha256digest', new_column_name='kdf_digest')
    op.add_column('user', sa.Column('kdf_options', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'ckey_encrypted', new_column_name='aeskey_encrypted')
    op.alter_column('user', 'kdf_digest', new_column_name='aeskey_sha256digest')
    op.drop_column('user', 'kdf_options')
    # ### end Alembic commands ###
