"""Add address column to explorer tx Output

Revision ID: aae9ec423e34
Revises: 62222eef7aa7
Create Date: 2024-08-21 20:14:22.593080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae9ec423e34'
down_revision: Union[str, None] = '62222eef7aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_output', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_output', 'address')
    # ### end Alembic commands ###
