"""Add index to blockchain_unspent.address

Revision ID: cf38519996ed
Revises: fe72df2d9ae4
Create Date: 2024-09-05 16:20:30.406161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf38519996ed'
down_revision: Union[str, None] = 'fe72df2d9ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blockchain_unspent_address'), 'blockchain_unspent', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockchain_unspent_address'), table_name='blockchain_unspent')
    # ### end Alembic commands ###
