"""Add network column to blockchain_transaction

Revision ID: fa2219e1174b
Revises: a79fed245af3
Create Date: 2024-08-31 14:56:44.299581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2219e1174b'
down_revision: Union[str, None] = 'a79fed245af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('network', sa.Enum('mainnet', 'testnet', name='networktype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'network')
    # ### end Alembic commands ###
