"""Remove unique constraint from explorer Input

Revision ID: fe72df2d9ae4
Revises: 35fc7eadd533
Create Date: 2024-09-04 18:58:44.703014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe72df2d9ae4'
down_revision: Union[str, None] = '35fc7eadd533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blockchain_input_outxid_vout_key', 'blockchain_input', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('blockchain_input_outxid_vout_key', 'blockchain_input', ['outxid', 'vout'])
    # ### end Alembic commands ###
