# Generated by Django 4.2.7 on 2023-11-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('string', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('icon_id', models.CharField(max_length=100)),
                ('public', models.BinaryField(max_length=128)),
                ('private', models.BinaryField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('inputs_amount', models.IntegerField()),
                ('outputs_amount', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('inputs_count', models.IntegerField()),
                ('outputs_count', models.IntegerField()),
                ('confirmations', models.IntegerField()),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('raw', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Unspent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80)),
                ('vout', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_txid', models.CharField(max_length=64)),
                ('from_vout', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.transaction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='unspent',
            constraint=models.UniqueConstraint(fields=('transaction', 'vout'), name='unspent_unique_tx_vout'),
        ),
        migrations.AddConstraint(
            model_name='input',
            constraint=models.UniqueConstraint(fields=('from_txid', 'from_vout'), name='input_unique_tx_vout'),
        ),
    ]
