# Generated by Django 4.2.7 on 2023-11-20 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='from_txid',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='input',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='creator.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='unspent',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unspents', to='creator.transaction'),
        ),
    ]
