# Generated by Django 4.2.7 on 2023-11-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_input_from_txid_alter_input_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_string', models.CharField(max_length=80)),
                ('vout', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='unspent',
            name='unspent_unique_tx_vout',
        ),
        migrations.RemoveField(
            model_name='unspent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='unspent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unspent',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='unspent',
            name='vout',
        ),
        migrations.AlterField(
            model_name='unspent',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unspents', to='creator.address'),
        ),
        migrations.AddField(
            model_name='output',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='creator.transaction'),
        ),
        migrations.AddField(
            model_name='unspent',
            name='output',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='unspent', serialize=False, to='creator.output'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='output',
            constraint=models.UniqueConstraint(fields=('transaction', 'vout'), name='unspent_unique_tx_vout'),
        ),
    ]
