# Generated by Django 4.1.2 on 2022-10-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('string', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=30)),
                ('public', models.CharField(max_length=128)),
                ('private', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CachedAddress',
            fields=[
                ('string', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CachedInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.cachedaddress')),
            ],
        ),
        migrations.CreateModel(
            name='CachedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_index', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.cachedaddress')),
            ],
        ),
        migrations.CreateModel(
            name='CachedTransaction',
            fields=[
                ('txid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('inputs_amount', models.IntegerField()),
                ('outputs_amount', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('inputs_count', models.IntegerField()),
                ('outputs_count', models.IntegerField()),
                ('confirmations', models.IntegerField()),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('raw', models.TextField()),
                ('inputs', models.ManyToManyField(related_name='as_input_transactions_set', through='creator.CachedInput', to='creator.cachedaddress')),
                ('outputs', models.ManyToManyField(related_name='as_output_transactions_set', through='creator.CachedOutput', to='creator.cachedaddress')),
            ],
        ),
        migrations.AddField(
            model_name='cachedoutput',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.cachedtransaction'),
        ),
        migrations.AddField(
            model_name='cachedinput',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.cachedtransaction'),
        ),
    ]
