# Generated by Django 4.1.2 on 2022-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedtransaction',
            name='inputs',
            field=models.ManyToManyField(related_name='as_input_transaction_set', through='creator.CachedInput', to='creator.cachedaddress'),
        ),
        migrations.AlterField(
            model_name='cachedtransaction',
            name='outputs',
            field=models.ManyToManyField(related_name='as_output_transaction_set', through='creator.CachedOutput', to='creator.cachedaddress'),
        ),
    ]
