# Generated by Django 4.1.2 on 2022-10-18 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('string', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=30)),
                ('public', models.CharField(max_length=80)),
                ('private', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CachedInput',
            fields=[
                ('string', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CachedOutput',
            fields=[
                ('string', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CachedTransaction',
            fields=[
                ('txid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('inputs_amount', models.FloatField()),
                ('outputs_amount', models.FloatField()),
                ('full_amount', models.FloatField()),
                ('fee', models.FloatField()),
                ('inputs_count', models.IntegerField()),
                ('outputs_count', models.IntegerField()),
                ('confirmations', models.IntegerField()),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('raw', models.TextField()),
                ('inputs', models.ManyToManyField(to='creator.cachedinput')),
                ('other_outputs', models.ManyToManyField(to='creator.cachedoutput')),
                ('output_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creator.address')),
            ],
        ),
    ]
