# Generated by Django 4.1.2 on 2022-10-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('string', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=30)),
                ('public', models.CharField(max_length=80)),
                ('private', models.CharField(max_length=80)),
                ('network', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CachedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField()),
                ('txid', models.CharField(max_length=100)),
                ('inps_count', models.IntegerField()),
                ('outs_count', models.IntegerField()),
                ('network', models.CharField(max_length=20)),
            ],
        ),
    ]
