# Generated by Django 4.1.2 on 2022-10-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='network',
        ),
        migrations.RemoveField(
            model_name='cachedtransaction',
            name='network',
        ),
    ]
